[theme]
base = "light"

[theme.light]
primaryColor = "#2A9D8F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"

[theme.dark]
primaryColor = "#2A9D8F"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
